apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: migration-job
        image: busybox:stable
        command: ["/bin/sh"]
        args: ["-c", "echo 'Running database migrations...' sleep 10 echo 'Migrated'"]
      restartPolicy: Never
  backoffLimit: 4
